### ISSUE TITLE
Implement passport based oauth in backend

### ISSUE THREAD

**Issue by sreehari2003** [DarkPhoenix2704/fossfolio#56]
##  TODO LIST

- [x] Remove Supertokens
- [x] add github oath
- [x] add google oauth
- [x] add email password auth

**Comment by DarkPhoenix2704** [comment]
So continue with Supabase or not?

**Comment by sreehari2003** [comment]
> So continue with Supabase or not?

for now, we can continue with the supabase if some people outside our team want to contribute they  can implement this. in the long term, we will shift to a standalone server one day.
